version: '3.7'

services:

  web:
    restart: always
    image: nodecloud/proxypanel
    volumes:
      - ./.caddy:/root/.caddy
      - storage_data:/www/wwwroot/proxypanel/storage
      - ./env:/www/wwwroot/proxypanel/.env
    ports:
      - "80:80"
    links:
      - db
      - redis

  db:
    image: mysql:oracle
    restart: always
    env_file: ./env
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes
    restart: always


volumes:
  db_data:
  redis_data:
  storage_data:
